apiVersion: v1
kind: Service
metadata:
  name: go-highload
  labels:
    app: go-highload
spec:
  type: NodePort
  selector:
    app: go-highload
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
